version: 2
updates:
  - package-ecosystem: docker
    directory: /testing
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - Bobgy
      - jlewi
      - pdmack
  - package-ecosystem: gomod
    directory: /components/common
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - Bobgy
      - jlewi
      - pdmack
  - package-ecosystem: docker
    directory: /components/access-management
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: docker
    directory: /components/admission-webhook
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - discordianfish
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: docker
    directory: /components/centraldashboard
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: docker
    directory: /components/crud-web-apps/jupyter
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: docker
    directory: /components/crud-web-apps/tensorboards
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: docker
    directory: /components/jupyter-web-app
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ioandr
      - elikatsis
      - kimwnasptd
      - thesuperzapper
      - StefanoFioravanzo
  - package-ecosystem: docker
    directory: /components/notebook-controller
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: docker
    directory: /components/profile-controller
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - kunmingg
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: docker
    directory: /components/tensorboard-controller
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kandrio98
      - kimwnasptd
  - package-ecosystem: docker
    directory: /components/tensorflow-notebook-image
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - pdmack
  - package-ecosystem: docker
    directory: /components/tensorflow-notebook-image/contrib/kaggle-notebook-image
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - pdmack
  - package-ecosystem: docker
    directory: /components/tensorflow-notebook-image/contrib/rapidsai-notebook-image
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - pdmack
  - package-ecosystem: npm
    directory: /components/centraldashboard
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: npm
    directory: /components/crud-web-apps/common/frontend/kubeflow-common-lib
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: npm
    directory: /components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: npm
    directory: /components/crud-web-apps/jupyter/frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: npm
    directory: /components/crud-web-apps/tensorboards/frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: npm
    directory: /components/jupyter-web-app/frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ioandr
      - elikatsis
      - kimwnasptd
      - thesuperzapper
      - StefanoFioravanzo
  - package-ecosystem: pip
    directory: /components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: pip
    directory: /components/crud-web-apps/jupyter/backend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: pip
    directory: /components/crud-web-apps/tensorboards/backend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
  - package-ecosystem: pip
    directory: /components/jupyter-web-app/backend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ioandr
      - elikatsis
      - kimwnasptd
      - thesuperzapper
      - StefanoFioravanzo
  - package-ecosystem: pip
    directory: /components/tensorflow-notebook-image
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - pdmack
  - package-ecosystem: gomod
    directory: /components/access-management
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: gomod
    directory: /components/admission-webhook
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - discordianfish
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: gomod
    directory: /components/notebook-controller
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: gomod
    directory: /components/profile-controller
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kimwnasptd
      - kunmingg
      - StefanoFioravanzo
      - thesuperzapper
      - yanniszark
  - package-ecosystem: gomod
    directory: /components/tensorboard-controller
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - elikatsis
      - kandrio98
      - kimwnasptd
