updates:
- assignees:
  - elikatsis
  - kimwnasptd
  - kunmingg
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/profile-controller
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/jupyter
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/tensorboards
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/access-management
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - pdmack
  directory: /components/tensorflow-notebook-image
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - pdmack
  directory: /components/tensorflow-notebook-image/contrib/kaggle-notebook-image
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - pdmack
  directory: /components/tensorflow-notebook-image/contrib/rapidsai-notebook-image
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kandrio98
  - kimwnasptd
  directory: /components/tensorboard-controller
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/notebook-controller
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - MartinForReal
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/centraldashboard
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - avdaredevil
  - SachinVarghese
  schedule:
    interval: daily
- assignees:
  - discordianfish
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/admission-webhook
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - ioandr
  - elikatsis
  - kimwnasptd
  - thesuperzapper
  - StefanoFioravanzo
  directory: /components/jupyter-web-app
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - avdaredevil
  - prodonjs
  - vkoukis
  schedule:
    interval: daily
- assignees:
  - Bobgy
  - jlewi
  - pdmack
  directory: /testing
  open-pull-requests-limit: 10
  package-ecosystem: docker
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/jupyter/frontend
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/tensorboards/frontend
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/common/frontend/kubeflow-common-lib
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/common/frontend/kubeflow-common-lib/dist/kubeflow
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/centraldashboard
  open-pull-requests-limit: 10
  package-ecosystem: npm
  reviewers:
  - avdaredevil
  - SachinVarghese
  schedule:
    interval: daily
- assignees:
  - ioandr
  - elikatsis
  - kimwnasptd
  - thesuperzapper
  - StefanoFioravanzo
  directory: /components/jupyter-web-app/frontend
  open-pull-requests-limit: 10
  package-ecosystem: npm
  reviewers:
  - avdaredevil
  - prodonjs
  - vkoukis
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/jupyter/backend
  open-pull-requests-limit: 10
  package-ecosystem: pip
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/tensorboards/backend
  open-pull-requests-limit: 10
  package-ecosystem: pip
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  directory: /components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend
  open-pull-requests-limit: 10
  package-ecosystem: pip
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - pdmack
  directory: /components/tensorflow-notebook-image
  open-pull-requests-limit: 10
  package-ecosystem: pip
  schedule:
    interval: daily
- assignees:
  - ioandr
  - elikatsis
  - kimwnasptd
  - thesuperzapper
  - StefanoFioravanzo
  directory: /components/jupyter-web-app/backend
  open-pull-requests-limit: 10
  package-ecosystem: pip
  reviewers:
  - avdaredevil
  - prodonjs
  - vkoukis
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - kunmingg
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/profile-controller
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/access-management
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kandrio98
  - kimwnasptd
  directory: /components/tensorboard-controller
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  schedule:
    interval: daily
- assignees:
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/notebook-controller
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - MartinForReal
  schedule:
    interval: daily
- assignees:
  - Bobgy
  - jlewi
  - pdmack
  directory: /components/common
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  schedule:
    interval: daily
- assignees:
  - discordianfish
  - elikatsis
  - kimwnasptd
  - StefanoFioravanzo
  - thesuperzapper
  - yanniszark
  directory: /components/admission-webhook
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  schedule:
    interval: daily
version: 2
