# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
python_paths:
  # Need to place kubeflow/testing in front of kubeflow/kubeflow so that the
  # package can be correctly located.
  - kubeflow/testing/py
  - kubeflow/kubeflow/py
workflows:
  # Run unittests for the shared frontend code
  - py_func: kubeflow.kubeflow.ci.common_ui_tests.create_workflow
    name: common-ui
    job_types:
      - presubmit
    include_dirs:
      - components/crud-web-apps/common/frontend/kubeflow-common-lib/*
    kwargs: {}
  # post submit jobs
  - py_func: kubeflow.kubeflow.cd.jwa.create_workflow
    name: jwa-build
    job_types:
      - postsubmit
    include_dirs:
      - components/crud-web-apps/common/frontend/kubeflow-common-lib/*
      - components/crud-web-apps/jupyter/*
    kwargs: {}
  # - py_func: kubeflow.kubeflow.cd.access_management.create_workflow
  #   name: access-management-build
  #   job_types:
  #     - presubmit
  #   include_dirs:
  #     - components/access-management/*
  #   kwargs: {}
  - py_func: kubeflow.kubeflow.cd.admission_webhook.create_workflow
    name: admission-webhook-build
    job_types:
      - presubmit
    include_dirs:
      - components/admission-webhook/*
    kwargs: {}
  - py_func: kubeflow.kubeflow.cd.central_dashboard.create_workflow
    name: central-dashboard-build
    job_types:
      - presubmit
    include_dirs:
      - components/centraldashboard/*
    kwargs: {}
  - py_func: kubeflow.kubeflow.cd.twa.create_workflow
    name: twa-build
    job_types:
      - presubmit
    include_dirs:
      - components/crud-web-apps/common/frontend/kubeflow-common-lib/*
      - components/crud-web-apps/tensorboards/*
    kwargs: {}
  - py_func: kubeflow.kubeflow.cd.notebook_controller.create_workflow
    name: notebook-controller-build
    job_types:
      - presubmit
    include_dirs:
      - components/common/*
      - components/notebook-controller/*
    kwargs: {}
  - py_func: kubeflow.kubeflow.cd.profile_controller.create_workflow
    name: profile-controller-build
    job_types:
      - presubmit
    include_dirs:
      - components/profile-controller/*
    kwargs: {}
  - py_func: kubeflow.kubeflow.cd.tensorboard_controller.create_workflow
    name: tensorboard-controller-build
    job_types:
      - presubmit
    include_dirs:
      - components/common/*
      - components/tensorboard-controller/*
    kwargs: {}
