# Configuration file for the Jupyter UI.
#
# Each Jupyter UI option is configured by two keys: 'value' and 'readOnly'
# - The 'value' key contains the default value
# - The 'readOnly' key determines if the option will be available to users
#
# If the 'readOnly' key is present and set to 'true', the respective option
# will be disabled for users and only set by the admin. Also when a
# Notebook is POSTED to the API if a necessary field is not present then
# the value from the config will be used.
#
# If the 'readOnly' key is missing (defaults to 'false'), the respective option
# will be available for users to edit.
#
# Note that some values can be templated. Such values are the names of the
# Volumes as well as their StorageClass
spawnerFormDefaults:
  baseImage:
    # The container Image for the user's Jupyter Notebook
    # If readonly, this value must be a member of the list below
    value: davidspek/kubeflow-ubuntu-jupyter-base:0.5
    # The list of available standard container Images
    options:
      - davidspek/kubeflow-ubuntu-jupyter-base:0.5
      - davidspek/kubeflow-ubuntu-pytorch-base:0.1
      - davidspek/kubeflow-ubuntu-pytorch-base:0.1-cuda
      - davidspek/kubeflow-ubuntu-tensorflow-base:0.1
      - davidspek/kubeflow-ubuntu-tensorflow-base:0.1-cuda
      - davidspek/kubeflow-ubuntu-datascience-base:0.2
    # By default, custom container Images are allowed
    # Uncomment the following line to only enable standard container Images
    readOnly: false
  pipPackages:
    # CPU for user's Notebook
    value: pip
    readOnly: false
  condaPackages:
    # Memory for user's Notebook
    value: conda
    readOnly: false
  imageDestination:
    # Destionation for the built image
    value: davidspek/kubeflow-ubuntu-datascience-full:0.3-kaniko-image-builder
    readOnly: false

