apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: volumes-web-app
        image: public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        env:
        - name: APP_PREFIX
          value: $(VWA_PREFIX)
        - name: USERID_HEADER
          value: $(VWA_USERID_HEADER)
        - name: USERID_PREFIX
          value: $(VWA_USERID_PREFIX)
      serviceAccountName: service-account
      volumes:
      - configMap:
          name: config
        name: config-volume
