apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: image-builder-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-builder-role
subjects:
- kind: ServiceAccount
  name: image-builder
