apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: builder-web-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: builder-web-app
      app.kubernetes.io/name: builder-web-app
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: core
    kind: Service
  - group: core
    kind: ServiceAccount
  - group: networking.istio.io
    kind: VirtualService
  descriptor:
    type: builder-web-app
    version: v1beta1
    description: Provides a UI which allows the user to build notebook images.
    maintainers:
    - name: David van der Spek
      email: 
    owners:
    - name: David van der Spek
      email: 
    keywords:
     - argo
     - kaniko
     - notebooks  
    links:
    - description: About
      url: 
    - description: Docs
      url: https://www.kubeflow.org/docs/notebooks 
  addOwnerRef: true